parameters:
  virt:
    nic:
      default:
        # TODO, update name of KVM bridge interface
        eth0:
          bridge: br0
          model: virtio
    disk:
      default:
        - system:
            size: 50000
      small:
        - system:
            size: 30000
      medium:
        - system:
            size: 80000
      large:
        - system:
            size: 100000
      xlarge:
        - system:
            size: 150000
      huge:
        - system:
            size: 300000
